# A build pipeline to verify the integrity of PR builds
trigger:
  branches:
    include:
      - 'pr'

pool:
  name: Hosted VS2017
  demands: npm

steps:
  - task: Npm@1
    displayName: 'npm ci'
    inputs:
      command: custom
      verbose: false
      customCommand: ci

  - task: Npm@1
    displayName: 'npm test'
    inputs:
      command: custom
      verbose: false
      customCommand: run test:coverage

  - task: Npm@1
    displayName: 'npm build'
    inputs:
      command: custom
      verbose: false
      customCommand: 'run build'

  - task: PublishTestResults@2
    displayName: 'Publish Test Results **\*.trx'
    inputs:
      testResultsFormat: VSTest
      testResultsFiles: '**\*.trx'
      testRunTitle: 'Jest Test Results'

  - task: PublishCodeCoverageResults@1
    displayName: 'Publish Code Coverage Reports'
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml'
      reportDirectory: '$(System.DefaultWorkingDirectory)/coverage'
      failIfCoverageEmpty: true
